### ISSUE TITLE
SED-ML Aggregation function (New terms for count, stddev, variance)

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/KiSAO#93]
- count: number of non-zero elements
- mean
- median
- standard deviation
- variance
- length

**Comment by matthiaskoenig** [comment]
* standard error 

would be great in addition

**Comment by matthiaskoenig** [comment]
Can we add the remaining functions under https://bioportal.bioontology.org/ontologies/KISAO/?p=classes&conceptid=http%3A%2F%2Fwww.biomodels.net%2Fkisao%2FKISAO%23KISAO_0000824?
Is there a documentation how to update terms? I could add these myself to get up to speed how to do this.

- [x] `maximum` (KISAO_0000828): The maximum of a set of values, ignoring NaN entries.
- [x] `minimum` (KISAO_0000829 The minimum of a set of values, ignoring NaN entries.
- [x] `mean` (KISAO_0000825) The mean of a set of values, ignoring NaN entries.
- [x] `standard deviation` (KISAO_0000826): The standard deviation of a set of values, ignoring NaN entries.
- [x] `standard error` (KISAO_0000827): The standard error of a set of values, ignoring NaN entries.
- [ ] `maximum (not ignoring NaN)`: The maximum of a set of values.
- [ ] `minimum (not ignoring NaN)`: The minimum of a set of values.
- [ ] `mean (not ignoring NaN)` The mean of a set of values.
- [ ] `standard deviation (not ignoring NaN)`: The standard deviation of a set of values.
- [ ] `standard error (not ignoring NaN)`: The standard error of a set of values.
- [ ] `sum`: The sum of array elements over a given axis, ignoring Nan entries
- [ ] `sum (not ignoring NaN)`: 
- [ ] `product`: The product of array elements over a given axis, ignoring NaN entries.
- [ ] `product (not ignoring NaN)`: The product of array elements over a given axis, ignoring NaN entries.
- [ ] `cumsum`: Return the cumulative sum of the elements along a given axis, ignoring NaN entries.
- [ ] `cumsum (not ignoring NaN)`: Return the cumulative sum of the elements along a given axis.
- [ ] `cumprod`: Return the cumulative product of elements along a given axis, ignoring NaN entries.
- [ ] `cumprod (not ignoring NaN)`: Return the cumulative product of elements along a given axis.
- [ ] `count`: number of non-zero elements, ignoring NaN entries
- [ ] `count (not ignoring NaN)`: number of non-zero elements, ignoring NaN entries
- [ ] `length`: number of elements, ignoring NaN entries
- [ ] `length` (not ignoring NaN): number of elements, ignoring NaN entries
- [ ] `median`
- [ ] `median (not ignoring NaN)`
- [ ] `variance`
- [ ] `variance (not ignoring NaN)`

It would be amazing if we could change the labels so that we have:
- `mean (ignoring NaN)`
- `mean`

which is in line with how this normally works. I.e. the ignoring NaN functions are special versions of the normal functions.

**Comment by jonrkarr** [comment]
I put a brief guide to editing the ontology here: https://github.com/SED-ML/KiSAO/blob/dev/CONTRIBUTING.md#modifying-the-ontology. [Protege](https://protege.stanford.edu/) is a good editing tool. This makes it easy to see the relationships as you add terms. The existing terms are also a good reference.

Please also add a note about your changes to [CHANGELOG.md](https://github.com/SED-ML/KiSAO/blob/dev/CHANGELOG.md).

The GitHub action will automatically run the few tests.

I can take of releasing your changes as v2.22.

**Comment by jonrkarr** [comment]
I agree with labels such as `mean` and `mean (ignoring NaN)`. This is similar to the names of NumPy functions (`mean`, `nanmean`) and the default configuration of MATLAB (`mean(..., nanflag)`). The "default" should be to include NaN such the result of a mean over a NaN is NaN.

**Comment by matthiaskoenig** [comment]
The following terms have been added/updated. Pull request shortly:
- [x] `maximum ignoring NaN` (KISAO_0000828)
- [x] `minimum ignoring NaN` (KISAO_0000829
- [x] `mean ignoring NaN` (KISAO_0000825)
- [x] `standard deviation ignoring NaN` (KISAO_0000826)
- [x] `standard error ignoring NaN` (KISAO_0000827)
- [x] `maximum` (KISAO_0000830)
- [x] `minimum` (KISAO_0000840)
- [x] `mean` (KISAO_0000841)
- [x] `standard deviation` (KISAO_0000842)
- [x] `standard error`  (KISAO_0000843)
- [x] `sum ignoring NaN` (KISAO_0000844)
- [x] `sum` (KISAO_0000845) 
- [x] `product ignoring NaN` (KISAO_0000846)
- [x] `product` (KISAO_0000847)
- [x] `cumulative sum` (KISAO_0000848)
- [x] `cumulative sum  ignoring NaN` (KISAO_0000849)
- [x] `cumulative product ignoring NaN` (KISAO_0000850)
- [x] `cumulative product` (KISAO_0000851)
- [x] `count ignoring NaN` (KISAO_0000852): number of non-zero elements, ignoring NaN entries
- [x] `count` (KISAO_0000853): number of non-zero elements, ignoring NaN entries
- [x] `length ignoring NaN` (KISAO_0000854): number of elements, ignoring NaN entries
- [x] `length` (KISAO_0000855): number of elements, ignoring NaN entries
- [x] `median ignoring NaN` (KISAO_0000856)
- [x] `median` (KISAO_0000857)
- [x] `variance ignoring NaN` (KISAO_0000858)
- [x] `variance` (KISAO_0000859)
